export type Level = {
  npcSpawnpoint: [number, number];
  npcCount: number;
  endPortalCords: [number, number];
  blocks: string;
  cameraStartPos: [number, number];
  cameraStartZoom: number;
};

export const Levels: Level[] = [
  {
    npcSpawnpoint: [100, 205],
    npcCount: 10,
    endPortalCords: [1350, 655],
    cameraStartPos: [0, 0],
    cameraStartZoom: 1,
    blocks:
      "qqqqqqqqqqqqqqqqqqqqAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAVlUVAAAAAAAAAAAAAACAVlVVFQAAAAAAAAAAAACAVlVVVVUAAAAAAAAAAACAVlVVVVVVVQEAVAAAAACAVlVVVVVVVVVVVVVVVVWVVhVAVVVVVVVVVVVVVVWVVgAAAFRVVVVVVVVVBVWFFgAAAAAAAAAAVQAAAACABgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACFBgAAAAAAAAAAAAAAAECVFgAAAAAAAAAAAAAAAFSVFgAAAAAAAAAAAAAAAFWVVhUAAAAAAAAAAAAAQFWVVlVVAAAAAEBVVQBUVVWVVlVVVVVRVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVqqqqqqqqqqqqqqqqqqqq",
  },
  {
    npcSpawnpoint: [100, 205],
    npcCount: 10,
    endPortalCords: [1350, 655],
    cameraStartPos: [0, 0],
    cameraStartZoom: 1,
    blocks:
      "qqqqqqqqqqqqqqqqqqqqAgAAAAAAAAAAAAAAAACVAgAAAAAAAAAAAAAAAECVAgAAAAAAAAAAAAAAAFCFAgAAAAAAAAAAAAAAAFSFAgAAAAAAAAAAAAAAUFWBVgAAAAAAAAAAAAAAVBWAVlUAAAAAAAAAAABAVQWAVlVVVVUAAFAAAABQVQCAUlVVVVVVAVQAAABUVQCAAkAFQFVVVVUAAEBVUQCAAgAAAFBVVRUAAFAFUACAAgAAAABAVQEAAAAAVACAAgAAAAAAAAAAAAAAVACAAgAAAAAAAAAAAAAAFQCAAgAAAAAAAAAAAAAABQCAAgAAAAAAAAAAAABQAQCAAgAAAAAAAAAAAABQAACEAgAAAAAAAAAAAAAAAACEAgAAAAAAAAAAAAAAAACFAgAAAAAAAAAAAAAAAECFAgAAAAAAAAAAAAAAAECFAgAAQAUAVQEAAAAAAFCFAgAAVFVVVQUAAAAAAFCFAgBAVVVVVRUAAAAAAFSBAgBUVVVVVVUAAAAAAFSBAkBVBQBQVVUVAAAAAFWAAlBVAQAAQFVVBQAAAFWAAlUVAAAAAABVFQAAQBWAQlUFAAAAAABQVQEAQBWAUlUBAAAAAABAVQAAUAWAVlUAAAAAAAAAAAAAVAWAVhUAAAAAAAAAAAAAVAWAVhUAAAAAAAAAAAAAVAGAVgUAAAAAAAAAAAAAVQGAVgUAAAAAAAAAAABAVQCAVgEAAAAAAAAAAABQVQCAVgEAAAAAAAAAAABUFQCAVgAAAAAAAAAAAABVFQCAqqqqqqqqqqqqqqqqqqqq",
  },
];
