export type Level = {
  npcSpawnpoint: [number, number];
  endPortalCords: [number, number];
  blocks: string;
  cameraStartPos: [number, number];
  cameraStartZoom: number;
};

export const Levels: Record<string, Level> = {
  First: {
    npcSpawnpoint: [100, 1100],
    endPortalCords: [1000, 1000],
    cameraStartPos: [-5, 350],
    cameraStartZoom: 1,
    blocks:
      "qqqqqqqqqqqqqqqqqqqqAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVqqqqqqqqqqqqqqqqqqqq",
  },
};
