export type Level = {
  npcSpawnpoint: [number, number];
  endPortalCords: [number, number];
  blocks: string;
  cameraStartPos: [number, number];
  cameraStartZoom: number;
};

export const Levels: Record<string, Level> = {
  First: {
    npcSpawnpoint: [100, 205],
    endPortalCords: [1350, 655],
    cameraStartPos: [0, 0],
    cameraStartZoom: 1,
    blocks:
      "qqqqqqqqqqqqqqqqqqqqAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACAVlUVAAAAAAAAAAAAAACAVlVVFQAAAAAAAAAAAACAVlVVVVUAAAAAAAAAAACAVlVVVVVVVQEAVAAAAACAVlVVVVVVVVVVVVVVVVWVVhVAVVVVVVVVVVVVVVWVVgAAAFRVVVVVVVVVBVWFFgAAAAAAAAAAVQAAAACABgAAAAAAAAAAAAAAAACAAgAAAAAAAAAAAAAAAACFBgAAAAAAAAAAAAAAAECVFgAAAAAAAAAAAAAAAFSVFgAAAAAAAAAAAAAAAFWVVhUAAAAAAAAAAAAAQFWVVlVVAAAAAEBVVQBUVVWVVlVVVVVRVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVVlVVVVVVVVVVVVVVVVWVqqqqqqqqqqqqqqqqqqqq",
  },
};
